routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/admin');
});

Auth::routes();

Route::get('/admin', 'HomeController@index');

Route::resource('admin/leads', 'LeadsController');

Route::resource('admin/accounts', 'AccountController');

Route::resource('admin/providers', 'ProviderController');

Route::resource('admin/rules', 'RulesController');

Route::post('admin/rules/updateRulesOrder', 'RulesController@updateRulesOrder');


Route::resource('services', 'ServicesController');


//Route::get('mailable', function () {
//    $lead = App\Models\Leads::all()->first();
//    $rule = App\Models\Rules::all()->first();
//
//    return new App\Mail\LeadAnsweredMail($lead, $rule, true);
//});

app/Models/Account.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Account
 * @package App\Models
 * @version October 24, 2019, 3:50 pm UTC
 *
 * @property \App\Models\Provider provider
 * @property integer id
 * @property string internal_account_id
 * @property string account_name
 * @property string reply_email
 * @property string account_link
 * @property integer provider_id
 */
class Account extends Model
{
    use SoftDeletes;

    public $table = 'accounts';

    protected $dates = ['deleted_at'];

    public $fillable = [
        'id',
        'internal_account_id',
        'account_name',
        'account_link',
        'provider_id',
        'reply_email'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'internal_account_id' => 'string',
        'account_name' => 'string',
        'account_link' => 'string',
        'reply_email' => 'string',
        'provider_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'internal_account_id' => 'required',
        'account_name' => 'required',
        'account_link' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function provider()
    {
        return $this->belongsTo(\App\Models\Provider::class, 'provider_id', 'id');
    }

    public static function getNameById($id)
    {
        return self::query()->find($id)->account_name;
    }
}

app/Http/Controllers/AccountController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateAccountRequest;
use App\Http\Requests\UpdateAccountRequest;
use App\Repositories\AccountRepository;
use App\Http\Controllers\AppBaseController;
use App\Repositories\RulesRepository;
use Illuminate\Http\Request;
use Flash;
use Response;

class AccountController extends AppBaseController
{
    /** @var  AccountRepository */
    private $accountRepository;

    /** @var  RulesRepository */
    private $rulesRepository;

    public function __construct(
        AccountRepository $accountRepo,
        RulesRepository $rulesRepo
    ) {
        $this->middleware('auth');
        $this->accountRepository = $accountRepo;
        $this->rulesRepository = $rulesRepo;
    }

    /**
     * Display a listing of the Account.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $accounts = $this->accountRepository->all();

        return view('accounts.index')
            ->with('accounts', $accounts);
    }

    /**
     * Show the form for creating a new Account.
     *
     * @return Response
     */
    public function create()
    {
        return view('accounts.create');
    }

    /**
     * Store a newly created Account in storage.
     *
     * @param CreateAccountRequest $request
     *
     * @return Response
     */
    public function store(CreateAccountRequest $request)
    {
        $input = $request->all();

        $account = $this->accountRepository->create($input);

        Flash::success('Account saved successfully.');

        return redirect(route('accounts.index'));
    }

    /**
     * Display the specified Account.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $account = $this->accountRepository->find($id);
        if (empty($account)) {
            Flash::error('Account not found');

            return redirect(route('accounts.index'));
        }

        $rules = $this->rulesRepository->all(['account_id' => $id])->sortBy('sort_order');

        return view('accounts.show')->with('account', $account)->with('rules', $rules);
    }

    /**
     * Show the form for editing the specified Account.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $account = $this->accountRepository->find($id);

        if (empty($account)) {
            Flash::error('Account not found');

            return redirect(route('accounts.index'));
        }

        return view('accounts.edit')->with('account', $account);
    }

    /**
     * Update the specified Account in storage.
     *
     * @param int $id
     * @param UpdateAccountRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAccountRequest $request)
    {
        $account = $this->accountRepository->find($id);

        if (empty($account)) {
            Flash::error('Account not found');

            return redirect(route('accounts.index'));
        }

        $account = $this->accountRepository->update($request->all(), $id);

        Flash::success('Account updated successfully.');

        return redirect(route('accounts.index'));
    }

    /**
     * Remove the specified Account from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $account = $this->accountRepository->find($id);

        if (empty($account)) {
            Flash::error('Account not found');

            return redirect(route('accounts.index'));
        }

        $this->accountRepository->delete($id);

        Flash::success('Account deleted successfully.');

        return redirect(route('accounts.index'));
    }
}

resources/views/accounts/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Account
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'accounts.store']) !!}

                        @include('accounts.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/accounts/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Account
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($account, ['route' => ['accounts.update', $account->id], 'method' => 'patch']) !!}

                        @include('accounts.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/accounts/fields.blade.php
<!-- Account Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('internal_account_id', 'Account Id:') !!}
    {!! Form::text('internal_account_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Account Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_name', 'Account Name:') !!}
    {!! Form::text('account_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Account Link Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_link', 'Account Link:') !!}
    {!! Form::text('account_link', null, ['class' => 'form-control']) !!}
</div>

<!-- Reply Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('reply_email', 'Reply Email:') !!}
    {!! Form::email('reply_email', null, ['class' => 'form-control']) !!}
</div>

<!-- Provider Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('provider_id', 'Provider Id:') !!}
    {!! Form::text('provider_id', null, ['class' => 'form-control', 'disabled']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('accounts.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/accounts/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Accounts</h1>
        <h1 class="pull-right">
{{--           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('accounts.create') !!}">Add New</a>--}}
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('accounts.table')
            </div>
        </div>
        <div class="text-center">

        </div>
    </div>
@endsection

resources/views/accounts/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Account
        </h1>
        <a href="{!! route('accounts.index') !!}" class="btn btn-default">Back</a>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('accounts.show_fields')
                </div>
            </div>
        </div>
    </div>

    <section class="content-header">
        <h1>Rules</h1>
        <h1>
            <a class="btn btn-primary pull-right" style="margin-top: -25px;" href="{!! route('rules.create', ['account_id' => $account->id]) !!}">Add New</a>
        </h1>
    </section>

    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('rules.table', ['account_id' => $account->id])
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/accounts/show_fields.blade.php
<!-- Account Id Field -->
<div class="form-group">
    {!! Form::label('internal_account_id', 'Account Id:') !!}
    <p>{!! $account->internal_account_id !!}</p>
</div>

<!-- Account Name Field -->
<div class="form-group">
    {!! Form::label('account_name', 'Account Name:') !!}
    <p>{!! $account->account_name !!}</p>
</div>

<!-- Account Link Field -->
<div class="form-group">
    {!! Form::label('account_link', 'Account Link:') !!}
    <p>{!! $account->account_link !!}</p>
</div>

<!-- Reply Email Field -->
<div class="form-group">
    {!! Form::label('reply_email', 'Reply Email:') !!}
    <p>{!! $account->reply_email !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $account->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $account->updated_at !!}</p>
</div>

<!-- Provider Id Field -->
<div class="form-group">
    {!! Form::label('provider_id', 'Provider:') !!}
    <p>{!! \App\Models\Provider::getNameById($account->provider_id) !!}</p>
</div>

resources/views/accounts/table.blade.php
<div class="table-responsive">
    <table class="table table-hover" id="accounts-table">
        <thead>
            <tr>
                <th>Account Id</th>
                <th>Account Name</th>
                <th>Account Link</th>
                <th>Reply Email</th>
                <th>Provider</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($accounts as $account)
            <tr>
                <td>{!! $account->internal_account_id !!}</td>
                <td>{!! $account->account_name !!}</td>
                <td>{!! $account->account_link !!}</td>
                <td>{!! $account->reply_email !!}</td>
                <td>{!! \App\Models\Provider::getNameById($account->provider_id) !!}</td>
                <td>
                    {!! Form::open(['route' => ['accounts.destroy', $account->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('accounts.show', [$account->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                        <a href="{!! route('accounts.edit', [$account->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>